[package]
name = "ultrahonk_soroban_contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { git = "https://github.com/jayz22/rs-soroban-sdk", rev = "6b57b52c4c1b0f5dca35a9fc6f54ebd3bd3f052e" }
ultrahonk_rust_verifier = { git = "https://github.com/yugocabrio/ultrahonk-rust-verifier.git", rev = "c8e9d2673afa75c989264a83b199a6ac5c6ae0bd"}
# soroban-sdk = { path = "../rs-soroban-sdk/soroban-sdk"}
# ultrahonk_rust_verifier = { path = "./ultrahonk-rust-verifier"}

[dev-dependencies]
# Enable test helpers for local unit tests
soroban-sdk = { git = "https://github.com/jayz22/rs-soroban-sdk", rev = "6b57b52c4c1b0f5dca35a9fc6f54ebd3bd3f052e", features = ["testutils"] }
# soroban-sdk = { path = "../priv-soroban-sdk/soroban-sdk", features = ["testutils"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
